/*
drop table TAB_FORNECEDORES
drop table TAB_EMPRESA
drop table TAB_PRODUTOS
drop table TAB_ESTOQUE
drop table TAB_UF


SELECT * FROM TAB_FORNECEDORES
SELECT * FROM TAB_EMPRESA
SELECT * FROM TAB_PRODUTOS
SELECT * FROM TAB_ESTOQUE
SELECT * FROM TAB_UF
*/


CREATE TABLE TAB_UF (
	UF_ID INT PRIMARY KEY IDENTITY(1,1),
    UF_CIDADE NVARCHAR(50) NOT NULL,
    UF_ABREVIACAO CHAR(2) NOT NULL
)
CREATE INDEX IDX_UF_ABREVIACAO ON TAB_UF (UF_ID)

INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Acre', 'AC')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Alagoas', 'AL')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Amapá', 'AP')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Amazonas', 'AM')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Bahia', 'BA')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Ceará', 'CE')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Distrito Federal', 'DF')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Espírito Santo', 'ES')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Goiás', 'GO')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Maranhão', 'MA')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Mato Grosso', 'MT')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Mato Grosso do Sul', 'MS')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Minas Gerais', 'MG')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Pará', 'PA')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Paraíba', 'PB')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Paraná', 'PR')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Pernambuco', 'PE')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Piauí', 'PI')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Rio de Janeiro', 'RJ')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Rio Grande do Norte', 'RN')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Rio Grande do Sul', 'RS')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Rondônia', 'RO')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Roraima', 'RR')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Santa Catarina', 'SC')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('São Paulo', 'SP')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Sergipe', 'SE')
INSERT INTO TAB_UF (UF_CIDADE, UF_ABREVIACAO) VALUES ('Tocantins', 'TO')




CREATE TABLE TAB_EMPRESA
(
EMP_ID INT PRIMARY KEY IDENTITY(1,1),
EMP_NOME VARCHAR(100) NOT NULL,
EMP_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
EMP_CNPJ VARCHAR(20) NOT NULL,
EMP_INSC_ESTADUAL VARCHAR(20),
EMP_CEP VARCHAR(8),
EMP_ENDERECO VARCHAR(100) NOT NULL,
EMP_NUMERO_ENDERECO VARCHAR(10) NOT NULL,
EMP_COMPLEMENTO VARCHAR(50),
EMP_BAIRRO VARCHAR(50) NOT NULL,
EMP_CIDADE VARCHAR(50) NOT NULL,
EMP_UF VARCHAR(2) NOT NULL,
EMP_TELEFONE_1 VARCHAR (13),
EMP_TELEFONE_2 VARCHAR (13),
EMP_EMAIL VARCHAR(100),
EMP_SITE VARCHAR(200),
EMP_LINKEDIN VARCHAR(50),
EMP_INSTAGRAM VARCHAR(50),
EMP_FACEBOOK VARCHAR(50),
EMP_DATA_VCTO_DAS INT,
EMP_VALOR_DAS DECIMAL,
EMP_DATA_CADASTRO DATETIME,
EMP_DATA_ATUALIZACAO DATETIME
)



CREATE TABLE TAB_FORNECEDORES
(
FOR_ID INT PRIMARY KEY IDENTITY(1,1),
FOR_MARCA INT,
FOR_DISTRIBUIDORA VARCHAR(100) NOT NULL,
FOR_CNPJ VARCHAR(20) NOT NULL,
FOR_INSC_ESTADUAL VARCHAR(20),
FOR_CEP VARCHAR(10),
FOR_ENDERECO VARCHAR(100),
FOR_NUMERO_ENDERECO VARCHAR(10) NOT NULL,
FOR_COMPLEMENTO VARCHAR(50), 
FOR_BAIRRO VARCHAR(50),
FOR_CIDADE VARCHAR(50),
FOR_UF VARCHAR(2),
FOR_CONTATO VARCHAR(50),
FOR_TELEFONE_1 VARCHAR (13),
FOR_WHATSAPP_1 VARCHAR (1),
FOR_TELEFONE_2 VARCHAR (13),
FOR_EMAIL_1 VARCHAR(100),
FOR_EMAIL_2 VARCHAR(100),
FOR_SITE VARCHAR(100),
FOR_INSTAGRAM VARCHAR(50),
FOR_DATA_CADASTRO DATETIME,
FOR_DATA_ATUALIZACAO DATETIME
)


CREATE TABLE TAB_CLIENTE (
    CLI_ID INT PRIMARY KEY IDENTITY(1,1), 
    CLI_NOME VARCHAR(100) NOT NULL, 
	CLI_CPF_CNPJ VARCHAR(20),
	CLI_DATA_NASCIMENTO DATE,
	CLI_CEP VARCHAR(10),
    CLI_ENDERECO VARCHAR(100),
    CLI_NUMERO_ENDERECO VARCHAR(10) NOT NULL,
	CLI_COMPLEMENTO VARCHAR(50), 
	FOR_BAIRRO VARCHAR(50),
	CLI_CIDADE VARCHAR(50),
    CLI_UF VARCHAR(2),
	CLI_TELEFONE_1 VARCHAR(13),
	CLI_WHATSAPP_1 VARCHAR (1),
	CLI_TELEFONE_2 VARCHAR(13),
	FOR_WHATSAPP_2 VARCHAR (1),
    CLI_EMAIL VARCHAR(100) NOT NULL, 
	CLI_INSTAGRAM VARCHAR(50),
    CLI_FACEBOOK VARCHAR(50),    
    CLI_DATA_CADASTRO DATETIME,
	CLI_DATA_ATUALIZACAO DATETIME
)


CREATE TABLE TAB_PRODUTOS (
    PROD_ID INT PRIMARY KEY IDENTITY(1,1),
	PROD_FORNECEDOR_ID INT ,
    PROD_NOME VARCHAR(100) NOT NULL,
	PROD_CODIGO_BARRAS VARCHAR(50),
    PROD_SKU VARCHAR(50),
    PROD_PESO DECIMAL(10, 2),
    PROD_COMPRIMENTO DECIMAL(10, 2),
    PROD_LARGURA DECIMAL(10, 2),
    PROD_ALTURA DECIMAL(10, 2),
	PROD_COR VARCHAR(20),
	PROD_DESCRICAO VARCHAR(500),
    PROD_DATA_CADASTRO DATETIME,
    PROD_DATA_ATUALIZACAO DATETIME
)

CREATE TABLE TAB_RAQUETES (
    RAQ_ID INT PRIMARY KEY IDENTITY(1,1),
	RAQ_FORNECEDOR_ID INT,
    RAQ_NOME VARCHAR(100) NOT NULL,
	RAQ_PESO DECIMAL(10, 2),
    RAQ_BALANCO DECIMAL(10,2),
	RAQ_MAIN INT,
	RAQ_CROSS INT,
	RAQ_LIBRA_DE INT,
	RAQ_LIBRA_ATE INT,
	RAQ_MATERIAL VARCHAR(20),
	RAQ_CABECA INT,
	RAQ_DESCRICAO VARCHAR(500),
    RAQ_DATA_CADASTRO DATETIME,
    RAQ_DATA_ATUALIZACAO DATETIME
)


CREATE TABLE TAB_ENCORDOAMENTO (
    ENC_ID INT PRIMARY KEY IDENTITY(1,1),
	ENC_CLIENTE_ID INT ,
	ENC_FORNECEDOR_ID INT,
	ENC_NOME_RAQ_ID INT,
	ENC_PADRAO_ENCORDOAMENTO INT,
	ENC_MARCA_CORDA INT,
	ENC_MODELO_CORDA INT,
	ENC_LBS INT,
	ENC_DESCRICAO VARCHAR(500),
    ENC_DATA_CADASTRO DATETIME    
)


CREATE TABLE TAB_MARCAS (
	MAR_ID INT PRIMARY KEY IDENTITY(1,1),
	MAR_NOME VARCHAR(100) NOT NULL,
	MAR_DESCRICAO VARCHAR(500),
	MAR_DATA_CADASTRO DATETIME
)










CREATE TABLE TAB_ESTOQUE (
--EST_ID_PRODUTO INT FOREIGN KEY REFERENCES TAB_PRODUTOS(PROD_ID),
--EST_ID_FORNECEDOR INT FOREIGN KEY REFERENCES TAB_FORNECEDORES(FOR_ID),
EST_ID_PRODUTO INT,
EST_ID_FORNECEDOR INT,
EST_QTD INT,
EST_DATA_CADASTRO DATETIME,
EST_DATA_ATUALIZACAO DATETIME
)